import type { Pattern } from '../types';

export const defaultPatterns: Pattern[] = [
  {
    id: 'identity',
    name: 'Personal Identity',
    description: 'Extracts personal identity declarations',
    regex: '(My name is|I am|I\'m)\\s+([A-Z][a-z]+\\s+[A-Z][a-z]+)',
    priority: 11,
  },
  {
    id: 'name',
    name: 'Person Name',
    description: 'Extracts capitalized names',
    regex: '\\b([A-Z][a-z]+\\s+[A-Z][a-z]+)\\b',
    priority: 10,
  },
  {
    id: 'email',
    name: 'Email Address',
    description: 'Extracts email addresses',
    regex: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',
    priority: 10,
  },
  {
    id: 'url',
    name: 'URL',
    description: 'Extracts URLs',
    regex: 'https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)',
    priority: 9,
  },
  {
    id: 'phone',
    name: 'Phone Number',
    description: 'Extracts phone numbers',
    regex: '\\+?[1-9]\\d{1,14}|\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}',
    priority: 8,
  },
  {
    id: 'date',
    name: 'Date',
    description: 'Extracts dates in various formats',
    regex: '\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4}|\\d{4}[/-]\\d{1,2}[/-]\\d{1,2}',
    priority: 7,
  },
  {
    id: 'time',
    name: 'Time',
    description: 'Extracts time patterns',
    regex: '\\d{1,2}:\\d{2}(:\\d{2})?(\\s?[AaPp][Mm])?',
    priority: 6,
  },
  {
    id: 'hashtag',
    name: 'Hashtag',
    description: 'Extracts hashtags',
    regex: '#[a-zA-Z0-9_]+',
    priority: 5,
  },
  {
    id: 'mention',
    name: 'Mention',
    description: 'Extracts @mentions',
    regex: '@[a-zA-Z0-9_]+',
    priority: 5,
  },
  {
    id: 'currency',
    name: 'Currency',
    description: 'Extracts currency amounts',
    regex: '[$€£¥]\\s?\\d+(\\.\\d{2})?|\\d+(\\.\\d{2})?\\s?[$€£¥]',
    priority: 6,
  },
  {
    id: 'code_block',
    name: 'Code Block',
    description: 'Extracts markdown code blocks',
    regex: '```[\\s\\S]*?```',
    priority: 4,
  },
  {
    id: 'uuid',
    name: 'UUID',
    description: 'Extracts UUIDs',
    regex: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
    priority: 7,
  },
  {
    id: 'ip_address',
    name: 'IP Address',
    description: 'Extracts IPv4 addresses',
    regex: '\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b',
    priority: 8,
  },
  {
    id: 'markdown_link',
    name: 'Markdown Link',
    description: 'Extracts markdown links',
    regex: '\\[([^\\]]+)\\]\\(([^)]+)\\)',
    priority: 5,
  },
];